#!/usr/bin/env bash

#########
# Globals
#########

VERSION=0.0.2

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

######
# Help
######

show_help()
{
   # Display Help
   echo -e "${YELLOW}Description${NC}"
   echo -e "   Execute the PHPUnit command for a single package or all packages of this monorepo."
   echo -e
   echo -e "${YELLOW}Usage${NC}"
   echo -e "   phpunit [-h|p|l|V] [--ci] [--] [<package>]"
   echo -e
   echo -e "${YELLOW}Options${NC}"
   echo -e "   ${GREEN}-V, --version${NC}       Print this software version."
   echo -e "   ${GREEN}-h, --help${NC}          Print this help."
   echo -e "   ${GREEN}-p, --package${NC}       Package to test."
   echo -e "   ${GREEN}-l, --list${NC}          List all packages in the monorepo."
   echo -e "   ${GREEN}-i, --interactive${NC}   Interactive mode. Will ask to continue after each package."
   echo -e "   ${GREEN}--ci${NC}                Format output for CI software."
   echo

   exit 0
}

########
# Inputs
########

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
    case $1 in
        -V | --version)
            echo $VERSION
            exit 0
            ;;
        -h | --help)
            show_help
            ;;
        -p | --package)
            shift
            PACKAGE=$1
            ;;
        -l | --list)
            ./bin/monorepo-packages
            exit 0
            ;;
        -i | --interactive)
            INTERACTIVE="true"
            ;;
        -c | --ci )
            CI_RUN="true"
            ;;
    esac;
    shift;
done

if [[ "$1" == '--' ]]; then
    shift;
fi

if [[ "$1" ]]; then
    PACKAGE=$1;
fi

##############
# Main Program
##############

# testing a single package
test_package() {
    echo -e "${GREEN}Testing the [${NC} $1 ${GREEN}] package..."

    BOOTSTRAP=packages/"$1"/tests/bootstrap.php

    if [[ -f "$BOOTSTRAP" ]]; then
        BOOTSTRAP="--bootstrap $BOOTSTRAP"
    else
        BOOTSTRAP=""
    fi

    if [[ -z "$CI_RUN" ]]; then
        php vendor/bin/phpunit packages/"$1"/tests/ --coverage-text "$BOOTSTRAP"
        if [[ -n "$INTERACTIVE" ]]; then
            read -r -p 'Continue ?:[Y/n/r](Y) ' CONTINUE
            if [[ "$CONTINUE" == 'n' ]]; then
                exit 0;
            fi

            if [[ "$CONTINUE" == 'r' ]]; then
                test_package "$1";
            fi
        fi
    else
        php vendor/bin/phpunit packages/"$1"/tests/ --coverage-clover "build/logs/clover.xml" --coverage-text "$BOOTSTRAP"
        exit $?
    fi
}

if [[ -z "$PACKAGE" ]]; then
    echo "Testing all packages..."

    for PKG in $(./bin/monorepo-packages); do
        test_package "$PKG"
    done
else
    if ! ./bin/monorepo-packages --has "$PACKAGE"; then
        echo "The requested package is not available."
        echo "Here is a list of available packages:"
        for PKG in $(./bin/monorepo-packages); do
            echo "  - $PKG"
        done
        exit 1
    fi

    echo "Testing $PACKAGE package..."

    test_package "$PACKAGE"
fi

exit 0
