name: charcoal
type: php
docroot: ""
php_version: "8.5"
webserver_type: apache-fpm
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - XDEBUG_MODE=coverage,debug,develop
corepack_enable: false
